version: '3.9'

networks:
  default:
    driver: bridge

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - "5000:9000"
    volumes:
      - ./portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - default

  home_assistant:
    container_name: home_assistant
    image: homeassistant/home-assistant
    ports:
      - "5001:8123"
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
    volumes:
      - ./home_assistant:/config
    restart: unless-stopped
    networks:
      - default

volumes:
  portainer: