version: '3.9'

networks:
  default:
    driver: bridge

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - "5000:9000"
    volumes:
      - ./portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - default

  home_assistant:
    container_name: home_assistant
    image: homeassistant/home-assistant:latest
    ports:
      - "5001:8123"
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
    volumes:
      - ./home_assistant:/config
    restart: unless-stopped
    networks:
      - default

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "5002:3000"
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource,grafana-worldmap-panel,grafana-piechart-panel"
      GF_DEFAULT_INSTANCE_NAME: domocorp
      GF_SECURITY_ADMIN_USER: Domocorp
      GF_SECURITY_ADMIN_PASSWORD: D0m0c0rp!
    volumes:
      - ./grafana:/var/lib/grafana
    networks:
      - default

  influxdb:
    container_name: influxdb
    image: influxdb:2.7.4
    ports:
      - "5003:8086"
    environment:
      INFLUXDB_DB: db0
      INFLUXDB_ADMIN_USER: Domocorp
      INFLUXDB_ADMIN_PASSWORD: D0m0c0rp!
    volumes:
      - ./influxdb:/var/lib/influxdb2
    networks:
      - default